name: Rails AI Monitoring

on:
  schedule:
    # Run every day at 9 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual runs
  push:
    branches: [ main ]
    paths:
      - 'monitoring_script.rb'
      - '.github/workflows/monitoring.yml'

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        
    - name: Install dependencies
      run: |
        gem install net-http
        gem install json
        gem install uri
        
    - name: Run monitoring script
      run: ruby monitoring_script.rb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Add your API keys here when you get them
        # GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        # GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        
    - name: Upload monitoring results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: monitoring-results-${{ github.run_number }}
        path: monitoring_log_*.txt
        
    - name: Create monitoring report
      run: |
        echo "# Rails AI Monitoring Report - $(date)" > monitoring_report.md
        echo "" >> monitoring_report.md
        echo "## Run Information" >> monitoring_report.md
        echo "- **Date**: $(date)" >> monitoring_report.md
        echo "- **Commit**: ${{ github.sha }}" >> monitoring_report.md
        echo "- **Branch**: ${{ github.ref_name }}" >> monitoring_report.md
        echo "" >> monitoring_report.md
        
        if [ -f monitoring_log_*.txt ]; then
          echo "## Monitoring Results" >> monitoring_report.md
          echo "" >> monitoring_report.md
          cat monitoring_log_*.txt >> monitoring_report.md
        else
          echo "## No Issues Found" >> monitoring_report.md
          echo "No suspicious activity detected." >> monitoring_report.md
        fi
        
    - name: Upload monitoring report
      uses: actions/upload-artifact@v4
      with:
        name: monitoring-report-${{ github.run_number }}
        path: monitoring_report.md
        
    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('monitoring_report.md')) {
            const report = fs.readFileSync('monitoring_report.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🔍 Rails AI Monitoring Report\n\n${report}`
            });
          }
